# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import notification_service_pb2 as notification__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in notification_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NotificationServiceStub(object):
    """Notification microservice
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendVerificationCode = channel.unary_unary(
                '/notification_service.NotificationService/SendVerificationCode',
                request_serializer=notification__service__pb2.VerificationCodeRequest.SerializeToString,
                response_deserializer=notification__service__pb2.NotificationResponse.FromString,
                _registered_method=True)
        self.SendReservationNotification = channel.unary_unary(
                '/notification_service.NotificationService/SendReservationNotification',
                request_serializer=notification__service__pb2.ReservationNotificationRequest.SerializeToString,
                response_deserializer=notification__service__pb2.NotificationResponse.FromString,
                _registered_method=True)
        self.SendScheduleAddedItem = channel.unary_unary(
                '/notification_service.NotificationService/SendScheduleAddedItem',
                request_serializer=notification__service__pb2.ScheduleAddedItemRequest.SerializeToString,
                response_deserializer=notification__service__pb2.NotificationResponse.FromString,
                _registered_method=True)
        self.SendScheduleDeletedItem = channel.unary_unary(
                '/notification_service.NotificationService/SendScheduleDeletedItem',
                request_serializer=notification__service__pb2.ScheduleDeletedItemRequest.SerializeToString,
                response_deserializer=notification__service__pb2.NotificationResponse.FromString,
                _registered_method=True)
        self.SendScheduleEditedItem = channel.unary_unary(
                '/notification_service.NotificationService/SendScheduleEditedItem',
                request_serializer=notification__service__pb2.ScheduleEditedItemRequest.SerializeToString,
                response_deserializer=notification__service__pb2.NotificationResponse.FromString,
                _registered_method=True)


class NotificationServiceServicer(object):
    """Notification microservice
    """

    def SendVerificationCode(self, request, context):
        """Send email with verification code to login
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendReservationNotification(self, request, context):
        """Send notification that reservation was made / moved / cancelled via email
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendScheduleAddedItem(self, request, context):
        """Send notification that item was added to schedule for specific group or education programme
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendScheduleDeletedItem(self, request, context):
        """Send notification that item was deleted from schedule for specific group or education programme
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendScheduleEditedItem(self, request, context):
        """Send notification that item was edited in schedule for specific group or education programme
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendVerificationCode': grpc.unary_unary_rpc_method_handler(
                    servicer.SendVerificationCode,
                    request_deserializer=notification__service__pb2.VerificationCodeRequest.FromString,
                    response_serializer=notification__service__pb2.NotificationResponse.SerializeToString,
            ),
            'SendReservationNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.SendReservationNotification,
                    request_deserializer=notification__service__pb2.ReservationNotificationRequest.FromString,
                    response_serializer=notification__service__pb2.NotificationResponse.SerializeToString,
            ),
            'SendScheduleAddedItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SendScheduleAddedItem,
                    request_deserializer=notification__service__pb2.ScheduleAddedItemRequest.FromString,
                    response_serializer=notification__service__pb2.NotificationResponse.SerializeToString,
            ),
            'SendScheduleDeletedItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SendScheduleDeletedItem,
                    request_deserializer=notification__service__pb2.ScheduleDeletedItemRequest.FromString,
                    response_serializer=notification__service__pb2.NotificationResponse.SerializeToString,
            ),
            'SendScheduleEditedItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SendScheduleEditedItem,
                    request_deserializer=notification__service__pb2.ScheduleEditedItemRequest.FromString,
                    response_serializer=notification__service__pb2.NotificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notification_service.NotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('notification_service.NotificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotificationService(object):
    """Notification microservice
    """

    @staticmethod
    def SendVerificationCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification_service.NotificationService/SendVerificationCode',
            notification__service__pb2.VerificationCodeRequest.SerializeToString,
            notification__service__pb2.NotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendReservationNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification_service.NotificationService/SendReservationNotification',
            notification__service__pb2.ReservationNotificationRequest.SerializeToString,
            notification__service__pb2.NotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendScheduleAddedItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification_service.NotificationService/SendScheduleAddedItem',
            notification__service__pb2.ScheduleAddedItemRequest.SerializeToString,
            notification__service__pb2.NotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendScheduleDeletedItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification_service.NotificationService/SendScheduleDeletedItem',
            notification__service__pb2.ScheduleDeletedItemRequest.SerializeToString,
            notification__service__pb2.NotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendScheduleEditedItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification_service.NotificationService/SendScheduleEditedItem',
            notification__service__pb2.ScheduleEditedItemRequest.SerializeToString,
            notification__service__pb2.NotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
