# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import booking_service_pb2 as booking__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in booking_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookingServiceStub(object):
    """Notification microservice
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/booking_service.BookingService/HealthCheck',
                request_serializer=booking__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=booking__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.AddBuilding = channel.unary_unary(
                '/booking_service.BookingService/AddBuilding',
                request_serializer=booking__service__pb2.Building.SerializeToString,
                response_deserializer=booking__service__pb2.BuildingResponse.FromString,
                _registered_method=True)
        self.UpdateBuilding = channel.unary_unary(
                '/booking_service.BookingService/UpdateBuilding',
                request_serializer=booking__service__pb2.Building.SerializeToString,
                response_deserializer=booking__service__pb2.BuildingResponse.FromString,
                _registered_method=True)
        self.DeleteBuilding = channel.unary_unary(
                '/booking_service.BookingService/DeleteBuilding',
                request_serializer=booking__service__pb2.Building.SerializeToString,
                response_deserializer=booking__service__pb2.BuildingResponse.FromString,
                _registered_method=True)
        self.GetAllBuildings = channel.unary_unary(
                '/booking_service.BookingService/GetAllBuildings',
                request_serializer=booking__service__pb2.Empty.SerializeToString,
                response_deserializer=booking__service__pb2.AllBuildingsResponse.FromString,
                _registered_method=True)
        self.GetSingleBuilding = channel.unary_unary(
                '/booking_service.BookingService/GetSingleBuilding',
                request_serializer=booking__service__pb2.Building.SerializeToString,
                response_deserializer=booking__service__pb2.BuildingResponse.FromString,
                _registered_method=True)
        self.AddRoom = channel.unary_unary(
                '/booking_service.BookingService/AddRoom',
                request_serializer=booking__service__pb2.Room.SerializeToString,
                response_deserializer=booking__service__pb2.RoomResponse.FromString,
                _registered_method=True)
        self.UpdateRoom = channel.unary_unary(
                '/booking_service.BookingService/UpdateRoom',
                request_serializer=booking__service__pb2.Room.SerializeToString,
                response_deserializer=booking__service__pb2.RoomResponse.FromString,
                _registered_method=True)
        self.DeleteRoom = channel.unary_unary(
                '/booking_service.BookingService/DeleteRoom',
                request_serializer=booking__service__pb2.Room.SerializeToString,
                response_deserializer=booking__service__pb2.RoomResponse.FromString,
                _registered_method=True)
        self.GetAllRooms = channel.unary_unary(
                '/booking_service.BookingService/GetAllRooms',
                request_serializer=booking__service__pb2.Building.SerializeToString,
                response_deserializer=booking__service__pb2.AllRoomsResponse.FromString,
                _registered_method=True)
        self.GetSingleRoom = channel.unary_unary(
                '/booking_service.BookingService/GetSingleRoom',
                request_serializer=booking__service__pb2.Room.SerializeToString,
                response_deserializer=booking__service__pb2.RoomResponse.FromString,
                _registered_method=True)
        self.AddBooking = channel.unary_unary(
                '/booking_service.BookingService/AddBooking',
                request_serializer=booking__service__pb2.Booking.SerializeToString,
                response_deserializer=booking__service__pb2.BookingResponse.FromString,
                _registered_method=True)
        self.UpdateBooking = channel.unary_unary(
                '/booking_service.BookingService/UpdateBooking',
                request_serializer=booking__service__pb2.Booking.SerializeToString,
                response_deserializer=booking__service__pb2.BookingResponse.FromString,
                _registered_method=True)
        self.DeleteBooking = channel.unary_unary(
                '/booking_service.BookingService/DeleteBooking',
                request_serializer=booking__service__pb2.Booking.SerializeToString,
                response_deserializer=booking__service__pb2.BookingResponse.FromString,
                _registered_method=True)
        self.GetAllBookings = channel.unary_unary(
                '/booking_service.BookingService/GetAllBookings',
                request_serializer=booking__service__pb2.AllBookingsRequest.SerializeToString,
                response_deserializer=booking__service__pb2.AllBookingsResponse.FromString,
                _registered_method=True)
        self.GetSingleBooking = channel.unary_unary(
                '/booking_service.BookingService/GetSingleBooking',
                request_serializer=booking__service__pb2.Booking.SerializeToString,
                response_deserializer=booking__service__pb2.BookingResponse.FromString,
                _registered_method=True)


class BookingServiceServicer(object):
    """Notification microservice
    """

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBuilding(self, request, context):
        """Add new building to database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBuilding(self, request, context):
        """Update building fields by finding it by id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBuilding(self, request, context):
        """Delete building by finding it by id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllBuildings(self, request, context):
        """Get all buildings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSingleBuilding(self, request, context):
        """Get signle building by id and load all of it's relationships
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddRoom(self, request, context):
        """Add room to Building in database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRoom(self, request, context):
        """Update room fields by finding it by id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRoom(self, request, context):
        """Delete room by finding it by id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllRooms(self, request, context):
        """Get all rooms of the building and load all of it's relationships
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSingleRoom(self, request, context):
        """Get signle room by id and load all of it's relationships
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBooking(self, request, context):
        """Add booking item to database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBooking(self, request, context):
        """Update booking item fields by finding it by id    
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBooking(self, request, context):
        """Delete booking item by finding it by id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllBookings(self, request, context):
        """Get all booking items for a building | room | date | time_slot | user_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSingleBooking(self, request, context):
        """Get a single booking item by booking id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=booking__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=booking__service__pb2.HealthCheckResponse.SerializeToString,
            ),
            'AddBuilding': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBuilding,
                    request_deserializer=booking__service__pb2.Building.FromString,
                    response_serializer=booking__service__pb2.BuildingResponse.SerializeToString,
            ),
            'UpdateBuilding': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBuilding,
                    request_deserializer=booking__service__pb2.Building.FromString,
                    response_serializer=booking__service__pb2.BuildingResponse.SerializeToString,
            ),
            'DeleteBuilding': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBuilding,
                    request_deserializer=booking__service__pb2.Building.FromString,
                    response_serializer=booking__service__pb2.BuildingResponse.SerializeToString,
            ),
            'GetAllBuildings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllBuildings,
                    request_deserializer=booking__service__pb2.Empty.FromString,
                    response_serializer=booking__service__pb2.AllBuildingsResponse.SerializeToString,
            ),
            'GetSingleBuilding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSingleBuilding,
                    request_deserializer=booking__service__pb2.Building.FromString,
                    response_serializer=booking__service__pb2.BuildingResponse.SerializeToString,
            ),
            'AddRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRoom,
                    request_deserializer=booking__service__pb2.Room.FromString,
                    response_serializer=booking__service__pb2.RoomResponse.SerializeToString,
            ),
            'UpdateRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRoom,
                    request_deserializer=booking__service__pb2.Room.FromString,
                    response_serializer=booking__service__pb2.RoomResponse.SerializeToString,
            ),
            'DeleteRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRoom,
                    request_deserializer=booking__service__pb2.Room.FromString,
                    response_serializer=booking__service__pb2.RoomResponse.SerializeToString,
            ),
            'GetAllRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllRooms,
                    request_deserializer=booking__service__pb2.Building.FromString,
                    response_serializer=booking__service__pb2.AllRoomsResponse.SerializeToString,
            ),
            'GetSingleRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSingleRoom,
                    request_deserializer=booking__service__pb2.Room.FromString,
                    response_serializer=booking__service__pb2.RoomResponse.SerializeToString,
            ),
            'AddBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBooking,
                    request_deserializer=booking__service__pb2.Booking.FromString,
                    response_serializer=booking__service__pb2.BookingResponse.SerializeToString,
            ),
            'UpdateBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBooking,
                    request_deserializer=booking__service__pb2.Booking.FromString,
                    response_serializer=booking__service__pb2.BookingResponse.SerializeToString,
            ),
            'DeleteBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBooking,
                    request_deserializer=booking__service__pb2.Booking.FromString,
                    response_serializer=booking__service__pb2.BookingResponse.SerializeToString,
            ),
            'GetAllBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllBookings,
                    request_deserializer=booking__service__pb2.AllBookingsRequest.FromString,
                    response_serializer=booking__service__pb2.AllBookingsResponse.SerializeToString,
            ),
            'GetSingleBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSingleBooking,
                    request_deserializer=booking__service__pb2.Booking.FromString,
                    response_serializer=booking__service__pb2.BookingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'booking_service.BookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('booking_service.BookingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookingService(object):
    """Notification microservice
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking_service.BookingService/HealthCheck',
            booking__service__pb2.HealthCheckRequest.SerializeToString,
            booking__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddBuilding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking_service.BookingService/AddBuilding',
            booking__service__pb2.Building.SerializeToString,
            booking__service__pb2.BuildingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBuilding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking_service.BookingService/UpdateBuilding',
            booking__service__pb2.Building.SerializeToString,
            booking__service__pb2.BuildingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBuilding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking_service.BookingService/DeleteBuilding',
            booking__service__pb2.Building.SerializeToString,
            booking__service__pb2.BuildingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllBuildings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking_service.BookingService/GetAllBuildings',
            booking__service__pb2.Empty.SerializeToString,
            booking__service__pb2.AllBuildingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSingleBuilding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking_service.BookingService/GetSingleBuilding',
            booking__service__pb2.Building.SerializeToString,
            booking__service__pb2.BuildingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking_service.BookingService/AddRoom',
            booking__service__pb2.Room.SerializeToString,
            booking__service__pb2.RoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking_service.BookingService/UpdateRoom',
            booking__service__pb2.Room.SerializeToString,
            booking__service__pb2.RoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking_service.BookingService/DeleteRoom',
            booking__service__pb2.Room.SerializeToString,
            booking__service__pb2.RoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking_service.BookingService/GetAllRooms',
            booking__service__pb2.Building.SerializeToString,
            booking__service__pb2.AllRoomsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSingleRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking_service.BookingService/GetSingleRoom',
            booking__service__pb2.Room.SerializeToString,
            booking__service__pb2.RoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking_service.BookingService/AddBooking',
            booking__service__pb2.Booking.SerializeToString,
            booking__service__pb2.BookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking_service.BookingService/UpdateBooking',
            booking__service__pb2.Booking.SerializeToString,
            booking__service__pb2.BookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking_service.BookingService/DeleteBooking',
            booking__service__pb2.Booking.SerializeToString,
            booking__service__pb2.BookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking_service.BookingService/GetAllBookings',
            booking__service__pb2.AllBookingsRequest.SerializeToString,
            booking__service__pb2.AllBookingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSingleBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking_service.BookingService/GetSingleBooking',
            booking__service__pb2.Booking.SerializeToString,
            booking__service__pb2.BookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
